name: Health Check

on:
  schedule:
    - cron: "0 0 * * *" # Ejecutar una vez al día a medianoche UTC
  workflow_dispatch: # Permite ejecutar manualmente el flujo de trabajo

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-igs4.onrender.com/
          follow-redirect: false # Optional, defaults to "false"
          max-attempts: 3 # Optional, defaults to 1
          retry-delay: 5s # Optional, only applicable to max-attempts > 1
          retry-all: false # Optional, defaults to "false"
          cookie: "" # Optional, default is empty
          basic-auth: "" # Optional, default is empty

      - name: Send Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          echo "Health check status: $? >> debug.log
          if [ $? -eq 0 ]; then
            echo "The health check for the project {{ EVENT_PAYLOAD.repository.full_name }} was successful!" | Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9 --webhook-url $DISCORD_WEBHOOK
          else
            echo "The health check for the project {{ EVENT_PAYLOAD.repository.full_name }} has failed!" | Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9 --webhook-url $DISCORD_WEBHOOK
          fi
